/**
 * Curated universe of liquid, long-history US names. We anonymize the chart, so
 * the point isn't to recognize the ticker — it's to read the *setup*. Mixing
 * sectors and a range of behaviors keeps the daily problem varied.
 */
export const UNIVERSE: { ticker: string; company: string }[] = [
  { ticker: "AAPL", company: "Apple" },
  { ticker: "MSFT", company: "Microsoft" },
  { ticker: "AMZN", company: "Amazon" },
  { ticker: "GOOGL", company: "Alphabet" },
  { ticker: "META", company: "Meta Platforms" },
  { ticker: "NVDA", company: "NVIDIA" },
  { ticker: "TSLA", company: "Tesla" },
  { ticker: "JPM", company: "JPMorgan Chase" },
  { ticker: "V", company: "Visa" },
  { ticker: "JNJ", company: "Johnson & Johnson" },
  { ticker: "WMT", company: "Walmart" },
  { ticker: "PG", company: "Procter & Gamble" },
  { ticker: "DIS", company: "Walt Disney" },
  { ticker: "NFLX", company: "Netflix" },
  { ticker: "KO", company: "Coca-Cola" },
  { ticker: "PEP", company: "PepsiCo" },
  { ticker: "INTC", company: "Intel" },
  { ticker: "AMD", company: "Advanced Micro Devices" },
  { ticker: "BA", company: "Boeing" },
  { ticker: "NKE", company: "Nike" },
  { ticker: "SBUX", company: "Starbucks" },
  { ticker: "MCD", company: "McDonald's" },
  { ticker: "CRM", company: "Salesforce" },
  { ticker: "ORCL", company: "Oracle" },
  { ticker: "ADBE", company: "Adobe" },
  { ticker: "PYPL", company: "PayPal" },
  { ticker: "QCOM", company: "Qualcomm" },
  { ticker: "T", company: "AT&T" },
  { ticker: "XOM", company: "ExxonMobil" },
  { ticker: "CVX", company: "Chevron" },
  { ticker: "BAC", company: "Bank of America" },
  { ticker: "GE", company: "General Electric" },
  { ticker: "F", company: "Ford" },
  { ticker: "UBER", company: "Uber" },
  { ticker: "SHOP", company: "Shopify" },
  { ticker: "SQ", company: "Block" },
  { ticker: "COST", company: "Costco" },
  { ticker: "HD", company: "Home Depot" },
  { ticker: "CAT", company: "Caterpillar" },
  { ticker: "GS", company: "Goldman Sachs" },
];
